### PR TITLE
Add options to getQueryString(options)

### PR DESCRIPTION
**Pull request by signalwerk**
Pass on the options to [qs.stringify](https://github.com/ljharb/qs#stringifying)

This is not breaking since it's optional and the default behaviour is not changed. `MINOR` in [Semantic Versioning](https://semver.org/)

I refactored all the test to not include the encoding and add an additional encoding test if no options are passed to the function ( see → `Filter for text = "\/ []&?" URI encoded` in `src/__tests__/PackUnpackString.test.ts`)

### CODE REVIEW

**Comment by d34dman** [comment]
Hi @signalwerk,

Thanks for the Pull request. Much appreciated. 

I like this idea and have no problem in merging it.

TODO
- [ ]  Add Test to check behaviour of `getQueryString` without option. This should also double as regression test.

Let me know if you are interested in adding them. If not, then I plan to work on this in the weekend.

---
P.S. I mistook you for my colleague Stephan Huber (from Hamburg Germany).

**Comment by signalwerk** [comment]
@d34dman not sure what test you are asking to do. I think I added a test without optiions. But since I mention it in my first post you are probably speaking about something else. Can you help me here? [Did you see that?](https://github.com/signalwerk/drupal-jsonapi-params/blob/feature/stringify-options/src/__tests__/PackUnpackString.test.ts#L25)

**Comment by d34dman** [comment]
@signalwerk sorry for the confusion, I think I was blinded by the pure awesomeness of the pull request. Thank you!

**Comment by signalwerk** [comment]
@d34dman 😂 thank you for the merge and the compliment. and of course; thank you for the package.

**Comment by d34dman** [comment]
Hi @signalwerk , I was wondering you have a Drupal.org profile. I would like to give credits for contributing to this feature on Drupal.org as well.

**Comment by signalwerk** [comment]
@d34dman yes. I do have a profile. It's also called [signalwerk](https://www.drupal.org/u/signalwerk). Thank you.

**Comment by d34dman** [comment]
Done :)

**Comment by signalwerk** [comment]
@d34dman thank you! nice 🥳

**Pull request merged**
